### ISSUE TITLE
[기체 제작] 완제품 기체 구매

### ISSUE THREAD

**Issue by JinraeKim** [fdcl-nrf/flight-experiment#1]
해당 [실험 논문](https://www.researchgate.net/publication/344027717_Modelling_and_PID_control_system_integration_for_quadcopter_DJI_F450_attitude_stabilization) 및 [드론 키트](http://xcoptershop.cafe24.com/product/detail.html?product_no=30226&cate_no=7860&display_group=1) 사이트의 직접 문의를 통해 대략적인 스펙을 결정함.

- [x] 프레임 및 모터: [드론 키트](http://xcoptershop.cafe24.com/product/detail.html?product_no=30226&cate_no=7860&display_group=1) 이용
- [x] 배터리: 직접 문의 결과 14.8v, 4s (4셀), 3400mAh 정도를 추천함. [예시](http://xcoptershop.cafe24.com/product/detail.html?product_no=28149&cate_no=6501&display_group=1)
    - 배터리, 조종기는 품절 ㅠ
    >  성훈  16:46
    @한나 드론배터리와 조종기는 품절입니다 ㅠ 대체품으로 수정해주시거나 구매 보류/취소 여부를 말씀해주세요~
- ~~성훈의 조언에 따라, 스페어를 포함 3대정도 구매 예정~~

**Comment by JinraeKim** [comment]
@hnlee77 부탁할게요~
(@seong-hun 의 조언대로, 구글 스프레드시트를 만들어서 구매목록을 작성하기로 함)

**Comment by hnlee77** [comment]
구매목록에 작성하였음~

**Comment by JinraeKim** [comment]
@hnlee77 구매목록 링크도 걸어두면 좋을듯~

**Comment by hnlee77** [comment]
네 ~~[링크](https://docs.google.com/spreadsheets/d/12x8d2OGU-mOH--MLQTp5RApL5peLICt7BIvxS96Z7gI/edit?usp=sharing)~~ [링크](https://docs.google.com/spreadsheets/d/117B2D4FJ1neOgiEfhJ7en6_d-6Ji4FlAsmoOh8TVVnw/edit#gid=805480455)도 공유합니다~
